name: CI / CD for aloom-frontend

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: |
          docker login --username guigzougz --password ${{ secrets.GH_PAT }} ghcr.io

      # Build the front-end Docker image
      - name: Build and push the Frontend image
        run: |
          docker build . -f Dockerfile --tag ghcr.io/guigzouz/aloom-front-end:latest
          docker push ghcr.io/guigzouz/aloom-front-end:latest

  deploy_to_vps:
    needs: build_and_publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Log in to the Droplet and deploy using Docker Compose
      - name: Deploy to Droplet using Docker Compose
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Log in to GHCR on the Droplet
            echo ${{ secrets.GH_PAT }} | docker login ghcr.io -u guigzougz --password-stdin

            # Pull the latest front-end image
            docker pull ghcr.io/guigzouz/aloom-front-end:latest

            # Stop and remove any old containers (optional, based on your needs)
            cd /root/aloom-front

            # Fetch the latest code (in case any updates were made)
            git pull origin main

            # Rebuild and deploy using Docker Compose
            docker-compose down
            docker-compose up -d

            # Optional: Clean up unused images
            docker image prune -f
